"""Writes android/app/src/main/res/layout/today_widget.xml.

The layout is a table of twenty cells. Generated from one template per kind of
cell so they cannot drift apart in size, colour or id pattern, and checked
against the ids TodayWidgetProvider.kt names: a cell the provider writes to
and the layout does not have takes the whole widget down on the launcher.

Run from mobile/:  python tool/gen_today_widget.py
"""
import re
import sys

LABEL = "#BFE3D3"
MUTED = "#8FC7B0"
RULE = "#2A8466"
ACCENT = "#C8F7DC"

OUT = "android/app/src/main/res/layout/today_widget.xml"
PROVIDER = "android/app/src/main/kotlin/com/abos/abos_mobile/TodayWidgetProvider.kt"


def cell(id_, weight, size="12sp", color="#FFFFFF"):
    return f"""        <TextView
            android:id="@+id/{id_}"
            android:layout_width="0dp"
            android:layout_weight="{weight}"
            android:layout_height="wrap_content"
            android:gravity="end"
            android:text="—"
            android:textColor="{color}"
            android:textSize="{size}"
            android:textStyle="bold"
            android:maxLines="1" />"""


def head(string, weight):
    return f"""        <TextView
            android:layout_width="0dp"
            android:layout_weight="{weight}"
            android:layout_height="wrap_content"
            android:gravity="end"
            android:text="@string/{string}"
            android:textColor="{MUTED}"
            android:textSize="9sp"
            android:maxLines="1" />"""


def row(label, key):
    return f"""    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="3dp"
        android:gravity="center_vertical"
        android:orientation="horizontal">
        <TextView
            android:layout_width="0dp"
            android:layout_weight="1.1"
            android:layout_height="wrap_content"
            android:text="@string/{label}"
            android:textColor="{LABEL}"
            android:textSize="12sp"
            android:maxLines="1" />
{cell(f"widget_{key}_today", "1.3")}
{cell(f"widget_{key}_month", "1.3")}
{cell(f"widget_{key}_change", "0.9", size="11sp", color=ACCENT)}
    </LinearLayout>"""


def stacked(string, id_, weight="1"):
    return f"""        <LinearLayout
            android:layout_width="0dp"
            android:layout_weight="{weight}"
            android:layout_height="wrap_content"
            android:orientation="vertical">
            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="@string/{string}"
                android:textColor="{MUTED}"
                android:textSize="9sp"
                android:maxLines="1" />
            <TextView
                android:id="@+id/{id_}"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="—"
                android:textColor="#FFFFFF"
                android:textSize="12sp"
                android:textStyle="bold"
                android:maxLines="1" />
        </LinearLayout>"""


RULE_VIEW = f"""    <!-- A TextView with nothing in it, not a View. RemoteViews will not
         inflate android.view.View at all, and it takes the whole widget down
         with it: the launcher shows a "cannot load widget" tile where the
         figures were meant to be. -->
    <TextView
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:layout_marginTop="6dp"
        android:layout_marginBottom="4dp"
        android:background="{RULE}" />"""

XML = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by tool/gen_today_widget.py. Edit the generator, not this file.

  The day's money on the home screen: the owner's own set, in his order.
  Selling, spending, buying and collecting, each for today, for this month and
  against last month; then where the money is; then what is owed to the
  company, what it owes, and what stands on the shelf.

  Every cell starts as a dash and stays one until the app writes a figure
  into it. A dash says nothing is known. A zero would be a fact about the
  business, and this file has no way of knowing one.
-->
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/widget_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="@drawable/widget_background"
    android:paddingLeft="14dp"
    android:paddingRight="14dp"
    android:paddingTop="10dp"
    android:paddingBottom="10dp">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">
        <!-- Whose figures these are. Somebody can belong to more than one
             company, and unlabelled numbers from the wrong one are numbers
             somebody acts on (docs/Contract section 8, rule kha). -->
        <TextView
            android:id="@+id/widget_company"
            android:layout_width="0dp"
            android:layout_weight="1.1"
            android:layout_height="wrap_content"
            android:text=""
            android:textColor="#FFFFFF"
            android:textSize="9sp"
            android:textStyle="bold"
            android:maxLines="1"
            android:ellipsize="end" />
{head("widget_col_today", "1.3")}
{head("widget_col_month", "1.3")}
{head("widget_col_change", "0.9")}
    </LinearLayout>

{row("widget_row_sales", "sales")}
{row("widget_row_expense", "expense")}
{row("widget_row_purchase", "purchase")}
{row("widget_row_inflow", "inflow")}

{RULE_VIEW}

    <!-- Where the money is, by kind. Notes in a till can be spent this
         afternoon, a bank balance cannot, and money on the road is
         somebody's responsibility until it lands. -->
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">
{stacked("widget_cash", "widget_cash")}
{stacked("widget_mfs", "widget_mfs", "1.2")}
{stacked("widget_bank", "widget_bank")}
{stacked("widget_in_transit", "widget_in_transit")}
    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="5dp"
        android:gravity="center_vertical"
        android:orientation="horizontal">
        <TextView
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="wrap_content"
            android:text="@string/widget_total_money"
            android:textColor="{LABEL}"
            android:textSize="12sp" />
        <TextView
            android:id="@+id/widget_total_money"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="—"
            android:textColor="{ACCENT}"
            android:textSize="14sp"
            android:textStyle="bold" />
    </LinearLayout>

{RULE_VIEW}

    <!-- Owed to the company, owed by it, and standing on the shelf. -->
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">
{stacked("widget_receivable", "widget_receivable")}
{stacked("widget_payable", "widget_payable")}
{stacked("widget_stock_value", "widget_stock", "1.2")}
    </LinearLayout>

    <!-- When these figures were true. A widget that cannot say how old it is
         will eventually be believed on a morning it is a day stale. -->
    <TextView
        android:id="@+id/widget_asof"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="5dp"
        android:text=""
        android:textColor="{MUTED}"
        android:textSize="9sp"
        android:maxLines="1"
        android:ellipsize="end" />
</LinearLayout>
"""

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(XML)

kotlin = open(PROVIDER, encoding="utf-8").read()
wanted = set(re.findall(r"R\.id\.(\w+)", kotlin))
present = set(re.findall(r"@\+id/(\w+)", XML))
missing = sorted(wanted - present)

# A double hyphen inside an XML comment is illegal, and the manifest merger
# names only the file when it meets one.
bad_comment = any("--" in body for body in re.findall(r"<!--(.*?)-->", XML, re.S))

print(f"wrote {OUT}: {len(present)} ids, provider names {len(wanted)}, missing {missing}")
print(f"double hyphen inside a comment: {bad_comment}")
sys.exit(1 if missing or bad_comment else 0)
