# -*- coding: utf-8 -*-
"""The Android launcher icon, generated from the ABOS mark.

Run from mobile/:

    python tool/make_launcher_icons.py

Source: assets/branding/abos-icon-transparent.png — the teal "A" on a
transparent ground, copied from "G:\\ERP PROJECT\\for-ABOS app" on
26 September 2026. Change the mark there, copy it here, run this again.

Why a script and not flutter_launcher_icons: one fewer dependency, and the
one number that matters — how large the mark sits inside the adaptive
canvas — is written down below with its reason, instead of inside a
package's defaults.

What it writes, under android/app/src/main/res/:

  mipmap-*/ic_launcher.png             phones before Android 8
  mipmap-*/ic_launcher_foreground.png  the mark, for the adaptive icon
  mipmap-*/ic_launcher_monochrome.png  Android 13 themed icons
  mipmap-anydpi-v26/ic_launcher.xml    ties them together
  values/ic_launcher_background.xml    the ground colour

A side effect worth knowing: on Android 12 and later the launch splash is
drawn from this same icon, so until this existed every start of the app
showed Flutter's logo.
"""

import os

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
MOBILE = os.path.dirname(HERE)
SOURCE = os.path.join(MOBILE, 'assets', 'branding', 'abos-icon-transparent.png')
RES = os.path.join(MOBILE, 'android', 'app', 'src', 'main', 'res')

DENSITIES = {'mdpi': 1.0, 'hdpi': 1.5, 'xhdpi': 2.0, 'xxhdpi': 3.0, 'xxxhdpi': 4.0}

BACKGROUND = (255, 255, 255, 255)
BACKGROUND_HEX = '#FFFFFF'

# The adaptive canvas is 108dp, but a launcher shows only the middle 72dp and
# may cut that to a 66dp circle — the only area Android guarantees. The first
# try, 0.56, looked right in a square and clipped the A's left foot and the
# dot under a circle mask, which is what Samsung and Pixel launchers use. 0.46
# keeps both inside the 66dp circle; checked against circle, squircle and
# square masks on 26 September 2026.
FOREGROUND_WIDTH = 0.46

# Before Android 8 the icon is drawn as-is, so it carries its own ground: a
# white rounded square, and the mark a little larger since nothing will be
# cut away.
LEGACY_WIDTH = 0.72
LEGACY_RADIUS = 0.22


def place(mark, canvas_px, width_ratio, ground=None, radius=0.0):
    canvas = Image.new('RGBA', (canvas_px, canvas_px), (0, 0, 0, 0))
    if ground is not None:
        mask = Image.new('L', (canvas_px, canvas_px), 0)
        ImageDraw.Draw(mask).rounded_rectangle(
            (0, 0, canvas_px - 1, canvas_px - 1),
            radius=int(canvas_px * radius), fill=255)
        canvas.paste(Image.new('RGBA', canvas.size, ground), (0, 0), mask)

    w = round(canvas_px * width_ratio)
    h = round(w * mark.height / mark.width)
    scaled = mark.resize((w, h), Image.LANCZOS)
    canvas.alpha_composite(scaled, ((canvas_px - w) // 2, (canvas_px - h) // 2))
    return canvas


def monochrome(foreground):
    # Android 13 recolours this to the wallpaper's theme; only the alpha is
    # read, so the mark's shape is what survives, not its gradient.
    white = Image.new('RGBA', foreground.size, (255, 255, 255, 255))
    white.putalpha(foreground.split()[3])
    return white


def write(img, folder, name):
    path = os.path.join(RES, folder)
    os.makedirs(path, exist_ok=True)
    img.save(os.path.join(path, name), optimize=True)


def main():
    mark = Image.open(SOURCE).convert('RGBA')
    mark = mark.crop(mark.getbbox())

    for density, scale in DENSITIES.items():
        folder = 'mipmap-' + density
        fg = place(mark, round(108 * scale), FOREGROUND_WIDTH)
        write(fg, folder, 'ic_launcher_foreground.png')
        write(monochrome(fg), folder, 'ic_launcher_monochrome.png')
        write(place(mark, round(48 * scale), LEGACY_WIDTH,
                    ground=BACKGROUND, radius=LEGACY_RADIUS),
              folder, 'ic_launcher.png')

    os.makedirs(os.path.join(RES, 'mipmap-anydpi-v26'), exist_ok=True)
    with open(os.path.join(RES, 'mipmap-anydpi-v26', 'ic_launcher.xml'), 'w',
              encoding='utf-8') as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n'
                '<!-- Generated by tool/make_launcher_icons.py. -->\n'
                '<adaptive-icon xmlns:android='
                '"http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@color/ic_launcher_background"/>\n'
                '    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>\n'
                '    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>\n'
                '</adaptive-icon>\n')

    os.makedirs(os.path.join(RES, 'values'), exist_ok=True)
    with open(os.path.join(RES, 'values', 'ic_launcher_background.xml'), 'w',
              encoding='utf-8') as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n'
                '<!-- Generated by tool/make_launcher_icons.py. -->\n'
                '<resources>\n'
                '    <color name="ic_launcher_background">%s</color>\n'
                '</resources>\n' % BACKGROUND_HEX)

    print('launcher icons written under', RES)


if __name__ == '__main__':
    main()

